[project]
name = 'basic'
version = '1.0.0'
description = 'The basic version of the sheikhs app'
dependencies = [
	'flask',
	'psycopg2-binary',
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"
