[project]
name = 'canoe'
version = '2.0.0'
description = 'The second release of the sheikhs project'
dependencies = [
	'flask',
	'psycopg2-binary',
	'gunicorn'
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"
