[project]
name = 'src'
version = '2.1.3'
description = 'The second release of the Sheikhs application'
dependencies = [
	'flask',
	'psycopg2-binary',
	'gunicorn',
	'Flask-SQLAlchemy'
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"
